[package]
name = "botc-bot"
version = "0.1.0"
authors = ["Ethan <edv121@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["macros"] }
serenity = "0.10.2"